version: 1.0.{build}
os: Visual Studio 2015 RC
configuration: Release
platform:
- x86
shallow_clone: true
clone_depth: 10
environment:
  PATH: C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: apps/visualizer/emptyExample/emptyExample.vcxproj
  parallel: true
  verbosity: minimal
artifacts:
- path: apps/visualizer/emptyExample/bin
on_success:
- '7z a bin.zip apps\visualizer\emptyExample\bin'
- 'dir'
- 'set PATH=C:\msys64\usr\bin;%PATH%'
- 'C:\msys64\usr\bin\curl --fail -X POST https://content.dropboxapi.com/2/files/upload --header "Authorization: Bearer %DROPBOX_TOKEN%" --header "Dropbox-API-Arg: {\"path\": \"/%APPVEYOR_REPO_BRANCH%/windows_%PLATFORM%.zip\",\"mode\": \"add\",\"autorename\": false,\"mute\": false}" --header "Content-Type: application/octet-stream" --data-binary @bin.zip'
# curl is sending only 5 bytes http://help.appveyor.com/discussions/problems/4050-curl-deploy-to-bintray-only-uploads-3-bytes
