version: 1.0.{build}
os: Visual Studio 2015 RC
configuration: Release
platform:
- x86
shallow_clone: true
clone_depth: 10
environment:
  PATH: C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: apps/myapps/visualizer/visualizer.vcxproj
  parallel: true
  verbosity: minimal
artifacts:
- path: apps/myapps/visualizer/bin
